# use containers in Travis (instead of VMs)
sudo: false

# install Heroku CLI 
addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt
      
before_install:
  - openssl aes-256-cbc -K $encrypted_939c08394e3d_key -iv $encrypted_939c08394e3d_iv -in server.key.enc -out server.key -d

# install additional Heroku CLI plug-ins
before_script:
  - export SFDX_DISABLE_ENCRYPTION=true
  - heroku plugins:install salesforcedx
  - heroku force --help
  - heroku force:auth:jwt:grant --clientid $ConsumerKey --jwtkeyfile server.key --username $Username --setdefaultdevhubusername

script:
  - heroku force:org:list --verbose